create database CRUDProducts;

USE CRUDProducts;

CREATE TABLE USERS(
	MAIL_USR VARCHAR(50) PRIMARY KEY,
	PASSWORD_USR VARCHAR(50)
);

CREATE TABLE PRODUCTS(
	NAME_PRO VARCHAR(50) PRIMARY KEY,
	USER_PRO VARCHAR(50),
	STOCK_PRO INT,
	VALUE_PRO DECIMAL(9,2),
	ORDER_PRO INT,

	FOREIGN KEY(USER_PRO) REFERENCES USERS(MAIL_USR)
);

